SET GLOBAL event_scheduler = ON;

DROP EVENT IF EXISTS EV_ATUALIZA_ATRASADAS;
CREATE EVENT EV_ATUALIZA_ATRASADAS
ON SCHEDULE EVERY 1 MINUTE
STARTS CURRENT_TIMESTAMP
ON COMPLETION PRESERVE
DO
    UPDATE tarefas
    SET atrasada = TRUE
    WHERE prazo_tarefa < NOW()
      AND atrasada = FALSE;
