DELIMITER $$
CREATE TRIGGER HASH_APOS_INATIVACAO
   BEFORE UPDATE ON USUARIOS
   FOR EACH ROW
   BEGIN
      IF NEW.inativo = TRUE AND OLD.INATIVO = FALSE THEN
         SET NEW.SENHA_USUARIO = SHA2(NEW.SENHA_USUARIO,256);
         SET NEW.EMAIL = SHA2(NEW.EMAIL,256);
         SET NEW.CPF = SHA2(NEW.CPF,256);
      END IF;
   END $$
DELIMITER ;
